language: java
dist: trusty
sudo: required
install:
- sudo apt-get install google-chrome-stable
- wget -N https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip
  -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/bin/
- sudo chmod +x /usr/local/bin/chromedriver
addons:
  chrome: stable
jdk:
- oraclejdk11
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- cd shaungc-java-dev && mvn clean install && mvn exec:java
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  slack:
    rooms:
      secure: OUzeyMSZDeMuQ8ILjE4Gvk8nIIKafObwRq42tJj087SGjfsjA8wxCdXuGXIiCfNhAplcyxWEXSHbk5LPVJrVErqCwzQbxZPG4Qqmp/LE6t7sEgYDb2+9AEjFx51sSq2iJ/zLH009LyByyNbgocSU1urCvm7S4Yx1L9vIUIRWJUO0xFG7SCs5HA6LxErG2m30dV/YB47uL6PGdQCUA6nwtUxCAfLF0P3ZAn4f9SIop7xYWWyLkzk1FfJCtwQ88syO0nwsUjC6HDAmHdMTpVDE79WaTapD43u/JafEDJBd+GNjdbycYhzMh/Axhdd8BrdK1ENhqwsOwR6U+i8RSo7ySf9//DXlz+fhpCqACyCQvCVR1i5j2INUfqRaM263NrgbcNMWfF/wYTBnzG6pENzy8zMKJd+ufg8R/ZFZRx1SO0e2toRbjWTYwxjn2Kj79X1z+NAivdpO5x0ZI5a1tOGgyzLZ+hG2H3y27lTDKnRl7SNbX7KuKX5ZTUR+UCqD7MNQM4GHNjy0hrL5JlxZZbVK1IlDlwyz78cqVPVSREmxsywtI8+d2tWZoIqDVoNeVqA1BzapcLaq3uEbjYGRdBC19Y5G7EeFUUmAecU4lKqd0MRx1FS84klg0IeS+wB5zm20tBqjs5UiWzjTdzN5iGUl6bwA7C8mv0nZIT1cY4VvYbs=
    on_start: always
    on_success: always
    on_failure: always
    template:
    - "*%{repository_slug}: %{message}*"
    - "*Git commit:* %{commit_message}"
    - 'Build result: %{result} in %{duration}'
    - 'Commit hash: `%{commit}`'
    - 'Build details: %{build_url}'
